[build]
  command = "npx xertz"
  publish = "dist"

[[redirects]]
  from = "http://frosty-benz-141b70.netlify.com/*"
  to = "https://www.geekytidbits.com/:splat"  
  force = true

[[redirects]]
  from = "https://frosty-benz-141b70.netlify.com/*"
  to = "https://www.geekytidbits.com/:splat"  
  force = true

[[redirects]]
  from = "/feed"
  to = "/rss.xml"