---
- name: Remove apache2, nginx and passenger
  apt: name={{ item }} state=absent
  with_items:
    - apache2
    - nginx

- name: Install packages
  apt: name={{ item }} state=present
  with_items:
    - nginx-extras

- name: Remove the default app
  file:
    state: absent
    path: /etc/nginx/sites-enabled/default

- name: Remove the default app config if exists
  file:
    state: absent
    path: /etc/nginx/sites-enabled/default

- name: Remove the app's symlink if exists
  file:
    state: absent
    path: /etc/nginx/sites-enabled/{{ app_name }}

- name: Configure nginx for the app
  template: src=etc_nginx_sites-available.conf.j2 dest=/etc/nginx/sites-available/{{ app_name }} group=www-data owner=www-data force=yes

- name: Enable the app
  file:
    state: link
    src: /etc/nginx/sites-available/{{ app_name }}
    dest: /etc/nginx/sites-enabled/{{ app_name }}

- name: Restart nginx
  action: service name=nginx state=restarted
